"""empty message

Revision ID: 18eda290555f
Revises: b494108d18ef
Create Date: 2024-01-09 15:49:29.819022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18eda290555f'
down_revision = 'b494108d18ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees_meetings', sa.Column('employee_id', sa.Integer(), nullable=False))
    op.drop_constraint(None, 'employees_meetings', type_='foreignkey')
    op.create_foreign_key(op.f('fk_employees_meetings_employee_id_employees'), 'employees_meetings', 'employees', ['employee_id'], ['id'])
    op.drop_column('employees_meetings', 'employee.id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees_meetings', sa.Column('employee.id', sa.INTEGER(), nullable=False))
    op.drop_constraint(op.f('fk_employees_meetings_employee_id_employees'), 'employees_meetings', type_='foreignkey')
    op.create_foreign_key(None, 'employees_meetings', 'employees', ['employee.id'], ['id'])
    op.drop_column('employees_meetings', 'employee_id')
    # ### end Alembic commands ###
